#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y					+= pinctrl-uclass.o
obj-$(CONFIG_$(SPL_)PINCTRL_GENERIC)	+= pinctrl-generic.o

obj-$(CONFIG_PINCTRL_SANDBOX)	+= pinctrl-sandbox.o

obj-$(CONFIG_PINCTRL_UNIPHIER)	+= uniphier/
